module.exports={
configureWebpack:{
    resovle:{
      alias:{
        'assets':"@/assets",
        'common':"@/common",
        'com':"@/components",
        'net':"@/network",
        'views':"@/views",
      }
    }
  }
}